name: striot-gui
version: 0.1.0.0
github: "jonnyspruce/striot-gui"
license: BSD3
author: "Jonny Spruce"
maintainer: "jspruce94@gmail.com"
copyright: "2020 Jonny Spruce"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/jonnyspruce/striot-gui#readme>

dependencies:
  - base >= 4.7 && < 5
  - algebraic-graphs  >= 0.1
  - aeson >= 1.4.6.0
  - striot >= 0.1.0.4

library:
  source-dirs: src

executables:
  striot-gui-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - striot-gui

tests:
  striot-gui-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - striot-gui
