resolver: lts-15.1
packages:
  - .
extra-deps:
  - git: https://github.com/striot/striot.git
    commit: 1441100588615723481b9d7571dbb5b37bbd65d4
  - aeson-1.4.6.0
  - hspec-2.7.1
  - hw-kafka-client-3.0.0
  - net-mqtt-0.6.2.3
  - prometheus-2.1.3
  - store-0.7.2
  - store-core-0.4.4.2
  - store-streaming-0.2.0.0
  - th-utilities-0.2.3.1
